import fs from "node:fs";
import path from "node:path";
import type { Subtask } from "../state/types.js";

export interface SpecMetadata {
  task: string;
  workspace: string;
  createdAt: string;
  revision: number;
  jiraTickets: string[];
  researchTopics: string[];
}

export function generateSpec(
  subtasks: Subtask[],
  metadata: SpecMetadata,
): string {
  const lines: string[] = [];

  lines.push(`# Execution Spec`);
  lines.push(``);
  lines.push(`> Generated by harness-cli | Revision ${metadata.revision} | ${metadata.createdAt}`);
  lines.push(``);
  lines.push(`## Task`);
  lines.push(``);
  lines.push(metadata.task);
  lines.push(``);

  if (metadata.jiraTickets.length > 0) {
    lines.push(`## Jira Tickets`);
    lines.push(``);
    for (const ticket of metadata.jiraTickets) {
      lines.push(`- ${ticket}`);
    }
    lines.push(``);
  }

  if (metadata.researchTopics.length > 0) {
    lines.push(`## Research Topics`);
    lines.push(``);
    for (const topic of metadata.researchTopics) {
      lines.push(`- ${topic}`);
    }
    lines.push(``);
  }

  lines.push(`## Dependency Graph`);
  lines.push(``);
  lines.push("```");
  for (const st of subtasks) {
    const deps = st.dependsOn.length > 0
      ? ` --> [${st.dependsOn.join(", ")}]`
      : `     (no dependencies)`;
    lines.push(`[${st.id}] ${st.title}${deps}`);
  }
  lines.push("```");
  lines.push(``);

  lines.push(`## Subtasks`);
  lines.push(``);

  for (const st of subtasks) {
    lines.push(`### [${st.id}] ${st.title}`);
    lines.push(``);
    if (st.dependsOn.length > 0) {
      lines.push(`**Depends on:** ${st.dependsOn.map((d) => `[${d}]`).join(", ")}`);
      lines.push(``);
    }
    lines.push(`**Description:**`);
    lines.push(``);
    lines.push(st.description);
    lines.push(``);
    lines.push(`**Acceptance Criteria:**`);
    lines.push(``);
    lines.push(st.acceptanceCriteria);
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  return lines.join("\n");
}

export function saveSpec(
  specContent: string,
  workDir: string,
  runId: string,
): string {
  const specsDir = path.join(workDir, ".harness", "specs");
  fs.mkdirSync(specsDir, { recursive: true });

  const filename = `${runId}.md`;
  const specPath = path.join(specsDir, filename);
  fs.writeFileSync(specPath, specContent, "utf-8");

  return specPath;
}

export function saveDraftSpec(
  specContent: string,
  workDir: string,
): string {
  const specsDir = path.join(workDir, ".harness");
  fs.mkdirSync(specsDir, { recursive: true });

  const specPath = path.join(specsDir, "spec-draft.md");
  fs.writeFileSync(specPath, specContent, "utf-8");

  return specPath;
}

export function readDraftSpec(workDir: string): string | null {
  const specPath = path.join(workDir, ".harness", "spec-draft.md");
  if (!fs.existsSync(specPath)) return null;
  return fs.readFileSync(specPath, "utf-8");
}
